`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 02/24/2026 11:35:57 AM
// Design Name: 
// Module Name: axis_volume_controller_tb
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module axis_volume_controller_tb();
  
  reg sim_axis_clk = 1'b0;
  reg [3:0] sim_switches = 4'b1111;
  
  reg [23:0] sim_ADC_to_DUT_data = 24'h000000;
  reg sim_ADC_to_DUT_valid = 1'b0;
  wire sim_DUT_to_ADC_ready;
  reg sim_ADC_to_DUT_last = 1'b0;

  wire [23:0] sim_DUT_to_DAC_data;
  wire sim_DUT_to_DAC_valid; 
  reg sim_DAC_to_DUT_ready = 1'b0; 
  wire sim_DUT_to_DAC_last;
 
  initial begin
        $display($time, " << Starting the Simulation >>");
         
#160     sim_DAC_to_DUT_ready = 1'b1;
        
        sendPacket (24'h7611B3, 1'b0);
        sendPacket (24'h07B4F2, 1'b1);       

#10     sendPacket (24'h45AB12, 1'b0);
        sendPacket (24'h2D551F, 1'b1);
        
        $display($time, " << Stopping the Simulation >>");
  end
  
  //generate an oscillating clock signal as close to 22.58065 MHz (the actual clock generated by the 
  // generator) as possible. The actual desired clock is something else, to get us to 44.1kHz sampling rate
  // Either way, a 44285 ps period is only approximate even to the real clock. We need to divide that in
  // two and round to 22.143 ns to give us a clock of just a little over approx 22.580499 MHz
  always begin
    #22.143 sim_axis_clk <= ~sim_axis_clk;
  end
  
    //provide clk, switch inputs (4), and all AXIS lines in and out.
	
    axis_volume_controller #(
		.SWITCH_WIDTH(4),
		.DATA_WIDTH(24)
	) m_vc (
        .clk(sim_axis_clk),
        .sw(sim_switches),
        
        .s_axis_data(sim_ADC_to_DUT_data),
        .s_axis_valid(sim_ADC_to_DUT_valid),
        .s_axis_ready(sim_DUT_to_ADC_ready),
        .s_axis_last(sim_ADC_to_DUT_last),
        
        .m_axis_data(sim_DUT_to_DAC_data),
        .m_axis_valid(sim_DUT_to_DAC_valid),
        .m_axis_ready(sim_DAC_to_DUT_ready),
        .m_axis_last(sim_DUT_to_DAC_last)
    );
    
    // Send a packet into the DUT's slave interface as though data is coming from the ADC
    // Assert data lines, assert valid (asynchronously is fine), set last flag (or not)
    // wait until posedge clock, if ready signal is coming back from slave, return control
    task sendPacket (input [23:0] data, input last);
        begin
            sim_ADC_to_DUT_data = data;
            sim_ADC_to_DUT_last = last;
            sim_ADC_to_DUT_valid = 1'b1;
            
            @(posedge sim_axis_clk); //wait here until a clock edge before taking a look at the "Ready" signal. We don't care what ready is until we hit a clock edge.
            while (sim_DUT_to_ADC_ready == 1'b0) begin
                @(posedge sim_axis_clk); //wait here until posedge occurs at the same time the ready signal is high
            end

//            @((posedge sim_axis_clock) && (sim_DUT_to_ADC_ready)); //wait here until posedge occurs at the same time the ready signal is high
            #2 // wait a couple of nanoseconds before removing data from the lines
            sim_ADC_to_DUT_valid = 1'b0;   
            sim_ADC_to_DUT_last = 1'b0;  
            sim_ADC_to_DUT_data = 24'h000000; 
        end
    endtask
    
endmodule